version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deploy/vllm
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deploy/vllm/production
    schedule:
      interval: monthly
